# Generated by Django 5.1 on 2024-10-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_seller_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='is_recruiter',
        ),
    ]
